apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo_frontend
spec:
  replicas: 1 # Again, this can be scaled if needed
  selector:
    matchLabels:
      app: todo_frontend
  template:
    metadata:
      labels:
        app: todo_frontend
    spec:
      containers:
        - name: todo_frontend
          image: todo_frontend:latest # Replace with your actual frontend image
          ports:
            - containerPort: 3000
          env:
            - name: VITE_API_URL
              value: 'http://backend:8000' # Connect to the backend service
---
apiVersion: v1
kind: Service
metadata:
  name: todo_frontend
spec:
  selector:
    app: todo_frontend
  ports:
    - protocol: TCP
      port: 80 # Expose the frontend app on port 80 externally
      targetPort: 3000
  type: LoadBalancer # MetalLB will assign an external IP
