apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-sqlite-pv
  namespace: todo-app
spec:
  capacity:
    storage: 10Gi # Adjust the size as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/sqlite
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-sqlite-pvc
  namespace: todo-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # This should match the PV size
